[package]
name = "glow_mesh"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "glow triangle drawing abstraction"
repository = "https://github.com/pat-365/glowmesh"

[dependencies]
glow = "0.11.0"
minvect = "0.1.1"

[dev-dependencies]
glutin = "0.28"