[package]
name = "glow_mesh"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "glow triangle drawing abstraction"
repository = "https://github.com/ThePJB/glowmesh"

[dependencies]
glow = "0.11.0"
minimg = "0.1.2"
minvect = "0.1.3"
png = "0.17.10"

[dev-dependencies]
glutin = "0.28"
